import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Geist_Mono } from "next/font/google"; // import your font
import "./globals.css";
import 'leaflet/dist/leaflet.css';

// Plus Jakarta Sans font
const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // optional: choose weights you need
});

// Optional: keep Geist Mono if you want monospace somewhere
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jakartaSans.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
